syntax = "proto3";
package raft_service;

import "google/protobuf/empty.proto";

service RaftRPC {
    rpc SendRequestVote (google.protobuf.Empty) returns (RequestVote);
    rpc RequestVoteReply (RequestVote) returns (RequestVoteResponse);
    rpc SendAppendEntries (google.protobuf.Empty) returns (AppendEntries);
    rpc AppendEntriesReply (AppendEntries) returns (AppendEntriesResponse);
}

message RequestVote {
    uint32 term = 1;
    uint32 candidate_id = 2;
    uint32 last_log_index = 3;
    uint32 last_log_term = 4;
}

message RequestVoteResponse {
    uint32 term = 1;
    bool vote_granted = 2;
    uint32 id = 3;
}

message LogEntry {
    message Get {
        string key = 1;
        string value = 2;
    }

    message Set {
        string key = 1;
    }

    oneof Command {
        Get get = 1;
        Set set = 2;
    }
    uint32 term = 3;
}

message AppendEntries {
    uint32 term = 1;
    uint32 leader_id = 2;
    uint32 prev_log_term = 3;
    uint32 prev_log_index = 4;
    uint32 leader_commit = 5;
    repeated LogEntry entries = 6;
}

message AppendEntriesResponse {
    uint32 term = 1;
    bool success = 2;
    uint32 id = 3;
    optional uint32 conflicting_first_index = 4;
    optional uint32 conflicting_entry_term = 5;
}